name: Refresh Channel IDs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '55 9 * * *'

permissions:
  contents: write 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change to the version you prefer

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install the requests library
          
      - name: Generate channel info
        env:
          YOUTUBE_API_KEY: ${{ secrets.KEY_API_GOOGLE_CLOUD }}
        run: |
          python yt/scripts/channel_info.py 

      - name: Commit changes
        run: |
          git config --local user.email "github-action@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add .  
          git commit -m "Updated channel info" || echo "No changes to commit"
          git push

      - name: Clean up __pycache__
        run: |
          find . -name '__pycache__' -exec rm -r {} +
